%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Ollie/Documents/CarND/CarND-Unscented-Kalman-Filter-Project/build/output.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/08/05 12:05:01

clear all
close all
%% Initialize variables.
filename = '/Users/Ollie/Documents/CarND/CarND-Unscented-Kalman-Filter-Project/build/output.txt';
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
name = dataArray{:, 1};
value = dataArray{:, 2};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

%% Split sensor values
radar = value(name==1);
laser = value(name==0);

%% Plot NIS
figure
subplot(2,1,1)
hold on
threshold_R = 7.815;
plot([0, length(radar)],[threshold_R, threshold_R],'r--');
plot(radar)
ylim([0 20])
grid on
title('Radar');
subplot(2,1,2)
hold on
threshold_L = 5.991;
plot(laser)
plot([0, length(radar)],[threshold_L, threshold_L],'r--');
ylim([0 20])
title('Laser');
grid on

%% Save to file
h = gcf;
print(h, 'NIS Plot', '-dpng', '-r300');